name: Format
'on':
  workflow_dispatch: null
  push:
    branches:
      - main
jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17
      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--replace -a --skip-javadoc-formatting"
